In [1]:
ls ..

Dockerfile  Makefile   artifacts/  changelog.md  poetry.lock     src/
LICENSE     README.md  bin/        notebooks/    pyproject.toml

In [10]:
import dotenv
import os
import logging

# Load env variables from .env
dotenv.load_dotenv()

True

In [9]:
VICTIMIZATION_DATASET_URL = (
    "https://data.ojp.usdoj.gov/resource/gcuy-rt5g.json?$limit=100000"
)

In [ ]:
class DataLoader:
    """Class to load NCVS data from."""

    @staticmethod
    def load_data() -> pd.DataFrame:
        """Load raw NCVS data using their API endpoint.

        Returns:
            pd.DataFrame: raw NCVS dataset
        """

        try:
            data_json = requests.get(VICTIMIZATION_DATASET_URL).json()
        except Exception as e:
            logging.error(
                {"message": "Could not load victimization data.", "detail": str(e)}
            )
        df = pd.DataFrame(data_json)
        return df

In [8]:
# Load NCVS 
df = DataLoader.load_data()
df.head()

2023-08-26 16:37:00 logger [logger] INFO [50] {'process': 'DataLoader.load_data', 'message': 'Started.', 'args': 'removed'} [logger.py:62]
2023-08-26 16:37:06 logger [logger] INFO [50] {'process': 'DataLoader.load_data', 'message': 'Success.', 'duration': 5.6956} [logger.py:73]

,idper,yearq,year,ager,sex,hispanic,race,race_ethnicity,hincome1,hincome2,...,weapcat,injury,serious,treatment,offenderage,offendersex,offtracenew,wgtviccy,series,newwgt
0,210176836193319999999923301,2004.1,2004,2,2,2,2,2,1,-1,...,0,0,1,0,3,1,-1,1952.97373,1,1952.97373
1,254207015147069329204211203,2009.1,2009,1,1,2,1,1,7,-1,...,2,0,1,0,5,1,-1,5570.68773,1,5570.68773
2,210313595043196799999912102,2004.1,2004,4,1,2,1,1,5,-1,...,0,0,1,0,4,1,-1,3366.95748,1,3366.95748
3,252018211553075329282015501,2011.4,2011,3,1,1,1,6,5,-1,...,0,0,1,0,88,1,-1,6991.56061,1,6991.56061
4,210376205057919299999921201,2004.1,2004,2,1,2,1,1,6,-1,...,0,1,3,1,3,3,-1,2834.64905,1,2834.64905